created fe update profile with integration
harshavardhan-sureify/codebyte-fe pull request #18
Opened 2023-06-20 06:24 UTC by akhilarjun3-sureify

![Screenshot from 2023-06-20 11-45-48](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/d849fb48-cb69-4789-87b7-004b6472095f)
![Screenshot from 2023-06-20 11-45-57](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/dff19bb7-35cb-4d7b-83af-029eef2c3d38)
![Screenshot from 2023-06-20 11-46-36](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/bd7ed424-ff6a-4c97-9ce2-b37f4af27d8f)
![Screenshot from 2023-06-20 11-46-53](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/5244c705-2c8b-439a-bd18-a0a589adfe2c)
![Screenshot from 2023-06-20 11-47-55](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/f253baa7-4f2a-4640-b02f-cd9f16c8e0ad)

2023-06-20 07:20 UTC, harshavardhan-sureify commented on src/components/routes/AppRoutes.jsx
> +                            <Route path="profile" element={<UpdateProfile />}/>
add profile to admin too

2023-06-20 07:33 UTC, maniknr-sureify commented on src/components/user/UpdateProfile.jsx
> +        setuserData({ ...res.data.data.user, password: "3210@Abcd" });
what is password here ? hardcoded value?

2023-06-21 06:43 UTC, akhilarjun3-sureify commented on src/components/user/UpdateProfile.jsx
> +        setuserData({ ...res.data.data.user, password: "3210@Abcd" });
Yes.It is not appropriate to fetch password.So It is like a dummy password which will be hidden in the fe.

2023-06-21 06:54 UTC, akhilarjun3-sureify commented on src/components/routes/AppRoutes.jsx
> +                            <Route path="profile" element={<UpdateProfile />}/>
resolved.

2023-06-21 07:31 UTC, maniknr-sureify approved these changes

2023-06-21 10:18 UTC, harshavardhan-sureify approved these changes

2023-06-21 16:34 UTC, abhishekdundigalla-sureify commented on src/components/routes/AppRoutes.jsx
> +              <Route path="trigger" element={<Trigger />} />
which functionality of the application is part of the Trigger component ?

2023-06-21 16:35 UTC, abhishekdundigalla-sureify commented on src/components/routes/AppRoutes.jsx
> +              <Route path="profile" element={<UpdateProfile />} />
Rename UpdateProfile component to Profile

2023-06-21 16:38 UTC, abhishekdundigalla-sureify commented on src/components/routes/AppRoutes.jsx
> +import UpdateProfile from "../user/UpdateProfile";
rename UpdateProfile component name to Profile

2023-06-21 16:42 UTC, abhishekdundigalla-sureify commented on src/components/user/UpdateProfile.jsx
> +  const updateUser = async (data) => {
change updateUser function name to a meaningful one

2023-06-21 16:46 UTC, abhishekdundigalla-sureify commented on src/components/user/UpdateProfile.jsx
> +        setToaster("Wrong password");
do not use toasters for invalid / incorrect form fields, use them only for the actions like profile updated successfully / technical error.
you can directly display the form error messages in the form itself on top of above all form fields.

2023-06-21 16:47 UTC, abhishekdundigalla-sureify commented on src/components/user/UpdateProfile.jsx
> +        setToaster("Something went Wrong");
i think else case is not required, check once

2023-06-21 16:48 UTC, abhishekdundigalla-sureify commented on src/components/user/UpdateProfile.jsx
> +        setuserData({ ...res.data.data.user, password: "3210@Abcd" });
do not use hard-coded password value

2023-06-21 16:50 UTC, abhishekdundigalla-sureify commented on src/components/user/UpdateProfile.jsx
> +    fetchData();
change fetchData function name to a meaningful one

2023-06-21 16:53 UTC, abhishekdundigalla-sureify commented on src/constants.js
> +const updateProfile = GO_BASE_URL + "user/updateprofile";
rename updateProfile to updateUserProfile

2023-06-21 16:56 UTC, abhishekdundigalla-sureify commented on src/constants.js
>  export const ADMIN_ROUTES = [
why and where ADMIN_ROUTES are being used ?

2023-06-21 16:58 UTC, abhishekdundigalla-sureify requested changes
Complete the required changes

2023-06-22 09:25 UTC, akhilarjun3-sureify commented on src/components/routes/AppRoutes.jsx
> +              <Route path="trigger" element={<Trigger />} />
changed

2023-06-22 09:26 UTC, akhilarjun3-sureify commented on src/components/routes/AppRoutes.jsx
> +              {/* <Route index element={<PageNotFound />} /> */}
Removed

2023-06-22 09:26 UTC, akhilarjun3-sureify commented on src/components/routes/AppRoutes.jsx
> +import UpdateProfile from "../user/UpdateProfile";
renamed

2023-06-22 09:26 UTC, akhilarjun3-sureify commented on src/components/user/UpdateProfile.jsx
> +  const updateUser = async (data) => {
changed

2023-06-22 09:26 UTC, akhilarjun3-sureify commented on src/components/user/UpdateProfile.jsx
> +        setToaster("Wrong password");
changed

2023-06-22 09:26 UTC, akhilarjun3-sureify commented on src/components/user/UpdateProfile.jsx
> +        setToaster("Something went Wrong");
changed

2023-06-22 09:27 UTC, akhilarjun3-sureify commented on src/components/user/UpdateProfile.jsx
> +        setuserData({ ...res.data.data.user, password: "3210@Abcd" });
changed

2023-06-22 09:27 UTC, akhilarjun3-sureify commented on src/constants.js
> +const updateProfile = GO_BASE_URL + "user/updateprofile";
changed

2023-06-22 11:27 UTC, akhilarjun3-sureify commented on src/components/user/UpdateProfile.jsx
> +      setToaster(error.response.data.error);
changed

2023-06-22 11:32 UTC, abhishekdundigalla-sureify approved these changes

2023-06-22 11:35 UTC, Madhukar-Sureify approved these changes

2023-06-22 11:51 UTC, merged