integration of forget password
harshavardhan-sureify/codebyte-fe pull request #21
Opened 2023-06-26 14:00 UTC by rameshguptha-sureify

![Screenshot from 2023-06-26 19-27-29](https://github.com/harshavardhan-sureify/codebyte-fe/assets/134484297/20813d6b-0a8b-4289-a7d3-3371d861b876)
![Screenshot from 2023-06-26 19-27-33](https://github.com/harshavardhan-sureify/codebyte-fe/assets/134484297/67a8c9ef-5aab-4f4d-b874-e1dae78b36e2)
![Screenshot from 2023-06-26 19-27-43](https://github.com/harshavardhan-sureify/codebyte-fe/assets/134484297/b528fa79-8d13-4db3-8828-d44445b26af6)

2023-06-26 17:51 UTC, harshavardhan-sureify approved these changes

2023-06-27 04:59 UTC, akhilarjun3-sureify approved these changes

2023-06-27 15:57 UTC, abhishekdundigalla-sureify commented on src/components/forgot password/EmailPage.jsx
> +        disabled={!!prop.open}
what do you mean by !! ?

2023-06-27 15:58 UTC, abhishekdundigalla-sureify commented on src/components/forgot password/ForgetPassword.jsx
> +                    open={!!toast}
what do you mean by !! ?

2023-06-27 16:00 UTC, abhishekdundigalla-sureify commented on src/components/forgot password/ResetPage.jsx
> +        error={!!errors.npassword}
what do you mean by !! ?

2023-06-27 16:01 UTC, abhishekdundigalla-sureify commented on src/components/forgot password/ForgetPassword.jsx
> +const ForgetPassword = () => {
change component name to ForgotPassword

2023-06-27 16:01 UTC, abhishekdundigalla-sureify commented on src/components/forgot password/ResetPage.jsx
> +        error={!!errors.cpassword}
what do you mean by !! ?

2023-06-27 16:03 UTC, abhishekdundigalla-sureify requested changes
I have seen your code is not formatted in a proper way at some places, please install Prettier in VS Code and format the code using it.

2023-06-28 04:36 UTC, rameshguptha-sureify commented on src/components/routes/AppRoutes.jsx
> +    return (
made proper indentations

2023-06-28 04:38 UTC, rameshguptha-sureify commented on src/components/forgot password/EmailPage.jsx
> +        error={!!prop.errors}
to make the strings into boolean values we are using this. so that we can avoid the warnings in console

2023-06-28 04:38 UTC, rameshguptha-sureify commented on src/components/forgot password/ForgetPassword.jsx
> +                    open={!!toast}
to make the strings into boolean values we are using this. so that we can avoid the warnings in console

2023-06-28 04:39 UTC, rameshguptha-sureify commented on src/components/forgot password/ForgetPassword.jsx
> +const ForgetPassword = () => {
changed to forgot password

2023-06-28 14:42 UTC, abhishekdundigalla-sureify commented on src/components/forgot password/ForgetPassword.jsx
> +                    open={!!toast}
It is not the right syntax to use in React. Try to solve those console warnings in a different way.

2023-06-29 06:02 UTC, abhishekdundigalla-sureify approved these changes

2023-06-29 06:32 UTC, merged