completed getpoll answers FE and FE/BE integration
harshavardhan-sureify/codebyte-fe pull request #28
Opened 2023-06-29 15:54 UTC by maniknr-sureify

completed FE and Integration to show answers for polls

![image](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133857894/89872c0f-42a1-4da6-995a-c2360262cbe1)

2023-07-03 05:15 UTC, harshavardhan-sureify approved these changes

2023-07-03 11:49 UTC, akhilarjun3-sureify approved these changes

2023-07-04 06:30 UTC, abhishekdundigalla-sureify commented on src/components/admin/PollAnswers.jsx
> +        <React.Fragment>
you can directly use <></>

2023-07-04 06:31 UTC, abhishekdundigalla-sureify commented on src/components/user/EmptyDataContainer.jsx
> +        height: "80     vh",
remove space in between

2023-07-04 06:32 UTC, abhishekdundigalla-sureify commented on src/components/admin/PollAnswers.jsx
> +    React.useEffect(() => {
import useEffect and use it.

2023-07-04 06:32 UTC, abhishekdundigalla-sureify commented on src/components/admin/PollAnswers.jsx
> +            console.log(err);
remove log statements

2023-07-04 06:34 UTC, abhishekdundigalla-sureify commented on src/components/admin/PollAnswers.jsx
> +            </LoadingContainer>
instead of writing the above same part of logic in other components too, write a separate component for it and use accordingly wherever required.

2023-07-04 06:36 UTC, abhishekdundigalla-sureify requested changes
Please complete the required changes.

2023-07-04 07:08 UTC, maniknr-sureify commented on src/components/admin/PollAnswers.jsx
> +        <React.Fragment>
resolved

2023-07-04 07:08 UTC, maniknr-sureify commented on src/components/user/EmptyDataContainer.jsx
> +        height: "80     vh",
resolved

2023-07-04 07:09 UTC, maniknr-sureify commented on src/components/admin/PollAnswers.jsx
> +            console.log(err);
It will be handled during session termination so instead of leaving it empty ,I used log statement

2023-07-04 07:20 UTC, maniknr-sureify commented on src/components/admin/PollAnswers.jsx
> +    React.useEffect(() => {
resolved

2023-07-04 07:20 UTC, abhishekdundigalla-sureify approved these changes

2023-07-04 07:23 UTC, Madhukar-Sureify approved these changes

2023-07-04 07:44 UTC, merged