Story/ite 58/all polls tabs fe
harshavardhan-sureify/codebyte-fe pull request #32
Opened 2023-07-03 07:51 UTC by akhilarjun3-sureify

![Screenshot from 2023-07-03 13-19-45](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/2422b6aa-2eeb-4794-ab21-fee13327859f)
![Screenshot from 2023-07-03 13-19-52](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/a9fd84c3-d37d-4062-a78a-56a76a60b26f)
![Screenshot from 2023-07-03 13-19-59](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133852299/08aef356-1089-48cf-8661-1d3a9bd1cd3d)

2023-07-03 10:30 UTC, maniknr-sureify submitted a review, later dismissed
change All polls to polls in sidebar, Follow proper naming for tabs Active polls,Ended polls,upcoming polls

2023-07-03 10:37 UTC, maniknr-sureify commented
Remove conflicts

2023-07-04 07:16 UTC, rameshguptha-sureify approved these changes

2023-07-05 05:52 UTC, harshavardhan-sureify approved these changes

2023-07-05 06:03 UTC, abhishekdundigalla-sureify commented on src/components/routes/AppRoutes.jsx
please format this component code in a right way without any extra lines.

2023-07-05 06:05 UTC, abhishekdundigalla-sureify requested changes
Complete the required changes

2023-07-05 06:08 UTC, Madhukar-Sureify approved these changes

2023-07-05 06:15 UTC, akhilarjun3-sureify commented on src/components/routes/AppRoutes.jsx
changed

2023-07-05 06:23 UTC, abhishekdundigalla-sureify approved these changes

2023-07-05 06:43 UTC, merged