added use reactivate feature
harshavardhan-sureify/codebyte-fe pull request #41
Opened 2023-07-27 12:23 UTC by harshavardhan-sureify

![image](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133851977/f6a3a5a0-8aab-4c46-816e-2f530d0f8017)
![image](https://github.com/harshavardhan-sureify/codebyte-fe/assets/133851977/fb0b7b3d-2a9c-4c2a-9752-dccd27741a3b)

2023-07-28 09:12 UTC, akhilarjun3-sureify approved these changes

2023-07-28 09:14 UTC, maniknr-sureify approved these changes

2023-07-28 12:11 UTC, abhishekdundigalla-sureify commented on src/components/admin/AllUsers.jsx
> +    const [statusUpdateUser, setStatusUpdateUser] = useState({});
const [updateUserStatus, setUpdateUserStatus] = useState({});

2023-07-28 12:13 UTC, abhishekdundigalla-sureify commented on src/components/admin/AllUsers.jsx
> +    const submitUpdateUserStatus = () => {
updateUserStatus or changeUserStatus
change it to any one of the above

2023-07-28 12:14 UTC, abhishekdundigalla-sureify commented on src/components/admin/AllUsers.jsx
> +                            {statusUpdateUser.is_active === "1"
is it needed to check with "1" or just with 1
check once in the above part of logic too

2023-07-28 12:15 UTC, abhishekdundigalla-sureify requested changes
Please check comments

2023-07-30 13:52 UTC, harshavardhan-sureify commented on src/components/admin/AllUsers.jsx
> +    const [statusUpdateUser, setStatusUpdateUser] = useState({});
done

2023-07-30 13:53 UTC, harshavardhan-sureify commented on src/components/admin/AllUsers.jsx
> +    const submitUpdateUserStatus = () => {
done

2023-07-30 13:53 UTC, harshavardhan-sureify commented on src/components/admin/AllUsers.jsx
> +                            {statusUpdateUser.is_active === "1"
i checked the type of the is_active and it is string so i need to check with "1"

2023-07-31 05:51 UTC, abhishekdundigalla-sureify approved these changes

2023-07-31 07:32 UTC, merged